export default [{
    name: "xmlt-001",
    taskLink: "https://kodaktor.ru/g/web_intro",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/xmlt-001",
    ansLink: "./xmlt-001/"
}, {
    name: "xmlt-002",
    taskLink: "https://kodaktor.ru/g/xml_intro",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/xmlt-002",
    ansLink: "./xmlt-002/"
}, {
    name: "xmlt-003",
    taskLink: "https://kodaktor.ru/xmlt_003",
    codeLink: "",
    ansLink: "https://kodaktor.ru/xmlt_c5a87"
}, {
    name: "tern-001",
    taskLink: "https://kodaktor.ru/tern_001",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/tern-001",
    ansLink: ""
}, {
    name: "jsin-001",
    taskLink: "https://kodaktor.ru/jsin_001",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/jsin-001",
    ansLink: "./jsin-001/"
}, {
    name: "iife",
    taskLink: "https://kodaktor.ru/g/iife",
    codeLink: "",
    ansLink: "https://kodaktor.ru/2f3ffe3_0ae34"
}, {
    name: "ktln-001",
    taskLink: "https://kodaktor.ru/22022019",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/ktln-001",
    ansLink: "./ktln-001/"
}, {
    name: "func-001",
    taskLink: "https://kodaktor.ru/func_001",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/func-001",
    ansLink: ""
}, {
    name: "func-002",
    taskLink: "",
    codeLink: "",
    ansLink: "https://kodaktor.ru/func_f9722"
}, {
    name: "func-003",
    taskLink: "",
    codeLink: "",
    ansLink: "https://kodaktor.ru/func_f515b"
}, {
    name: "func-004",
    taskLink: "https://kodaktor.ru/func_004",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/func-004",
    ansLink: "https://kodaktor.ru/func_b3a5f"
}, {
    name: "func-005",
    taskLink: "",
    codeLink: "",
    ansLink: "https://kodaktor.ru/func_45fb9"
}, {
    name: "func-006",
    taskLink: "https://kodaktor.ru/func_006",
    codeLink: "",
    ansLink: "https://kodaktor.ru/func_ac156"
}, {
    name: "func-007",
    taskLink: "",
    codeLink: "",
    ansLink: "https://kodaktor.ru/func_6e900"
}, {
    name: "func-008",
    taskLink: "",
    codeLink: "",
    ansLink: "https://kodaktor.ru/func_d3c79"
}, {
    name: "func-009",
    taskLink: "",
    codeLink: "",
    ansLink: "https://kodaktor.ru/func_e4a8e"
}, {
    name: "func-010",
    taskLink: "https://kodaktor.ru/func_010",
    codeLink: "",
    ansLink: "https://kodaktor.ru/func_610f5"
}, {
    name: "async-task",
    taskLink: "https://kodaktor.ru/async_ed538",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/async-task",
    ansLink: "./async-task/"
}, {
    name: "rxjs-task",
    taskLink: "https://kodaktor.ru/13e5570",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/rxjs-task",
    ansLink: "./rxjs-task/"
}, {
    name: "prot-001",
    taskLink: "https://kodaktor.ru/prot_001",
    codeLink: "",
    ansLink: "https://kodaktor.ru/g/array.prototype"
}, {
    name: "prot-002",
    taskLink: "https://kodaktor.ru/prot_002",
    codeLink: "",
    ansLink: "https://repl.it/@quemsah/protochain"
}, {
    name: "! jsnd-001",
    taskLink: "https://kodaktor.ru/js01_intro_lr.pdf",
    codeLink: "",
    ansLink: ""
}, {
    name: "! json-intro",
    taskLink: "https://kodaktor.ru/g/json_intro",
    codeLink: "",
    ansLink: "./json-intro/"
}, {
    name: "startask",
    taskLink: "https://kodaktor.ru/startask",
    codeLink: "",
    ansLink: "https://kodaktor.ru/startask_83e6b"
}, {
    name: "! types-out",
    taskLink: "https://kodaktor.ru/types_out",
    codeLink: "",
    ansLink: ""
}, {
    name: "! ips-task",
    taskLink: "https://kodaktor.ru/g/ips_task",
    codeLink: "",
    ansLink: ""
}, {
    name: "! rsch-001",
    taskLink: "https://kodaktor.ru/g/rsch_001",
    codeLink: "",
    ansLink: ""
}, {
    name: "! evnt-001",
    taskLink: "https://kodaktor.ru/evnt_001",
    codeLink: "",
    ansLink: ""
}, {
    name: "! evnt-002",
    taskLink: "https://kodaktor.ru/evnt_002",
    codeLink: "",
    ansLink: ""
}, {
    name: "! evnt-003",
    taskLink: "https://kodaktor.ru/evnt_003",
    codeLink: "",
    ansLink: ""
}, {
    name: "! babl-001",
    taskLink: "https://kodaktor.ru/babl_001",
    codeLink: "",
    ansLink: ""
}, {
    name: "! babl-002",
    taskLink: "https://kodaktor.ru/babl_002",
    codeLink: "",
    ansLink: ""
}, {
    name: "iter-001",
    taskLink: "https://kodaktor.ru/iter_001",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/iter-001",
    ansLink: "https://kodaktor.ru/iter_9426f"
}, {
    name: "! mixer",
    taskLink: "https://kodaktor.ru/g/mixer",
    codeLink: "",
    ansLink: ""
}]