export default [{
    name: "xmlt-001",
    taskLink: "https://kodaktor.ru/g/web_intro",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/xmlt-001",
    ansLink: "./xmlt-001/"
}, {
    name: "xmlt-002",
    taskLink: "https://kodaktor.ru/g/xml_intro",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/xmlt-002",
    ansLink: "./xmlt-002/"
}, {
    name: "xmlt-003",
    taskLink: "https://kodaktor.ru/xmlt_003",
    codeLink: "",
    ansLink: "https://kodaktor.ru/xmlt_c5a87"
}, {
    name: "tern-001",
    taskLink: "https://kodaktor.ru/tern_001",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/tern-001",
    ansLink: ""
}, {
    name: "jsin-001",
    taskLink: "https://kodaktor.ru/jsin_001",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/jsin-001",
    ansLink: "./jsin-001/"
}, {
    name: "iife",
    taskLink: "https://kodaktor.ru/g/iife",
    codeLink: "",
    ansLink: "https://kodaktor.ru/2f3ffe3_0ae34"
}, {
    name: "ktln-001",
    taskLink: "https://kodaktor.ru/22022019",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/ktln-001",
    ansLink: "./ktln-001/"
}, {
    name: "func-001",
    taskLink: "https://kodaktor.ru/func_001",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/func-001",
    ansLink: ""
}, {
    name: "func-002",
    taskLink: "",
    codeLink: "",
    ansLink: "https://kodaktor.ru/func_f9722"
}, {
    name: "func-003",
    taskLink: "",
    codeLink: "",
    ansLink: "https://kodaktor.ru/func_f515b"
}, {
    name: "func-004",
    taskLink: "https://kodaktor.ru/func_004",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/func-004",
    ansLink: "https://kodaktor.ru/func_b3a5f"
}, {
    name: "func-005",
    taskLink: "",
    codeLink: "",
    ansLink: "https://kodaktor.ru/func_45fb9"
}, {
    name: "func-006",
    taskLink: "https://kodaktor.ru/func_006",
    codeLink: "",
    ansLink: "https://kodaktor.ru/func_ac156"
}, {
    name: "func-007",
    taskLink: "",
    codeLink: "",
    ansLink: "https://kodaktor.ru/func_6e900"
}, {
    name: "func-008",
    taskLink: "",
    codeLink: "",
    ansLink: "https://kodaktor.ru/func_d3c79"
}, {
    name: "func-009",
    taskLink: "",
    codeLink: "",
    ansLink: "https://kodaktor.ru/func_e4a8e"
}, {
    name: "func-010",
    taskLink: "https://kodaktor.ru/func_010",
    codeLink: "",
    ansLink: "https://kodaktor.ru/func_610f5"
}, {
    name: "async-task",
    taskLink: "https://kodaktor.ru/async_ed538",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/async-task",
    ansLink: "./async-task/"
}, {
    name: "rxjs-task",
    taskLink: "https://kodaktor.ru/13e5570",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/rxjs-task",
    ansLink: "./rxjs-task/"
}, {
    name: "prot-001",
    taskLink: "https://kodaktor.ru/prot_001",
    codeLink: "",
    ansLink: "https://kodaktor.ru/g/array.prototype"
}, {
    name: "prot-002",
    taskLink: "https://kodaktor.ru/prot_002",
    codeLink: "",
    ansLink: "https://repl.it/@quemsah/protochain"
}, {
    name: "~~ jsnd-001",
    taskLink: "https://kodaktor.ru/js01_intro_lr.pdf",
    codeLink: "",
    ansLink: ""
}, {
    name: "json-intro",
    taskLink: "https://kodaktor.ru/g/json_intro",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/json-intro",
    ansLink: ""
}, {
    name: "startask",
    taskLink: "https://kodaktor.ru/startask",
    codeLink: "",
    ansLink: "https://kodaktor.ru/startask_83e6b"
}, {
    name: "types-out",
    taskLink: "https://kodaktor.ru/types_out",
    codeLink: "",
    ansLink: "https://kodaktor.ru/types_c2766"
}, {
    name: "ips-task",
    taskLink: "https://kodaktor.ru/g/ips_task",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/ips-task",
    ansLink: "./ips-task/"
}, {
    name: "~~ rsch-001",
    taskLink: "https://kodaktor.ru/g/rsch_001",
    codeLink: "",
    ansLink: ""
}, {
    name: "evnt-001",
    taskLink: "https://kodaktor.ru/evnt_001",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/evnt-001",
    ansLink: "https://kodaktor.ru/evnt_fc3ce"
}, {
    name: "evnt-002",
    taskLink: "https://kodaktor.ru/evnt_002",
    codeLink: "",
    ansLink: "https://kodaktor.ru/custom_b69c2"
}, {
    name: "evnt-003",
    taskLink: "https://kodaktor.ru/evnt_003",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/evnt-003",
    ansLink: "./evnt-003/"
}, {
    name: "babl-001",
    taskLink: "https://kodaktor.ru/babl_001",
    codeLink: "",
    ansLink: "https://kodaktor.ru/babl_4b90f"
}, {
    name: "babl-002",
    taskLink: "https://kodaktor.ru/babl_002",
    codeLink: "",
    ansLink: "https://kodaktor.ru/bind02032018_d12c1"
}, {
    name: "iter-001",
    taskLink: "https://kodaktor.ru/iter_001",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/iter-001",
    ansLink: "https://kodaktor.ru/iter_9426f"
}, {
    name: "mixer",
    taskLink: "https://kodaktor.ru/g/mixer",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/mixer",
    ansLink: "./mixer/"
}, {
    name: "~~ fetch-audio",
    taskLink: "",
    codeLink: "https://codepen.io/quemsah/pen/VROdby",
    ansLink: "./fetch-audio/"
}, {
    name: "~ to do: ->",
    taskLink: "",
    codeLink: "",
    ansLink: ""
}, {
    name: "~~ xsl-intro",
    taskLink: "https://kodaktor.ru/g/xsl_intro",
    codeLink: "",
    ansLink: ""
}, {
    name: "cart",
    taskLink: "https://kodaktor.ru/g/cart",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/cart",
    ansLink: "./cart/"
}, {
    name: "bndl-001",
    taskLink: "https://kodaktor.ru/g/bndl_001",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/bndl-001",
    ansLink: "./bndl-001/"
}, {
    name: "canv-001",
    taskLink: "http://kodaktor.ru/cnvs/lr_canvas_rates.pdf",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/canv-001",
    ansLink: "./canv-001/"
}, {
    name: "frmw-001",
    taskLink: "https://kodaktor.ru/frmw_001",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/frmw-001",
    ansLink: "./frmw-001/"
}, {
    name: "frmw-002",
    taskLink: "https://kodaktor.ru/frmw_002",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/frmw-002",
    ansLink: "./frmw-002/dist"
}, {
    name: "frmw-003",
    taskLink: "https://kodaktor.ru/frmw_003",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/frmw-003",
    ansLink: "./frmw-003/dist"
}, {
    name: "frmw-004",
    taskLink: "https://kodaktor.ru/frmw_004",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/frmw-004",
    ansLink: "./frmw-004/dist"
}, {
    name: "frmw-005",
    taskLink: "https://kodaktor.ru/frmw_005",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/frmw-005",
    ansLink: "./frmw-005/dist"
}, {
    name: "frmw-006",
    taskLink: "https://kodaktor.ru/frmw_006",
    codeLink: "",
    ansLink: "https://ellie-app.com/5tDr6vCpbcra1"
}, {
    name: "frmw-007",
    taskLink: "https://kodaktor.ru/frmw_007",
    codeLink: "https://github.com/quemsah/itmo-labs/tree/master/frmw-007",
    ansLink: "./frmw-007/"
}, {
    name: "you",
    taskLink: "https://kodaktor.ru/you",
    codeLink: "",
    ansLink: "./you/"
}]